using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Synto.Generators;

/// <summary>Emits the canonical <c>System.Runtime.CompilerServices.InterceptsLocationAttribute</c>
/// definition (which the SDK does not ship) that a version-stamped <c>[InterceptsLocation]</c> binds to.
/// The interceptor method body itself stays the author's concern.</summary>
public static class Interceptors
{
    public const string AttributeHintName = "InterceptsLocationAttribute.g.cs";

    // MUST stay byte-identical to the ObjectReader example's previous const (Task 3 snapshot is unchanged).
    public const string AttributeSource =
        """
        // <auto-generated/>
        namespace System.Runtime.CompilerServices
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
            internal sealed class InterceptsLocationAttribute : global::System.Attribute
            {
                public InterceptsLocationAttribute(int version, string data)
                {
                    _ = version;
                    _ = data;
                }
            }
        }
        """;

    public static void AddDefinition(SourceProductionContext context) =>
        context.AddSource(AttributeHintName, SourceText.From(AttributeSource, Encoding.UTF8));

    public static void AddDefinition(IncrementalGeneratorPostInitializationContext context) =>
        context.AddSource(AttributeHintName, SourceText.From(AttributeSource, Encoding.UTF8));
}
